20.Б10-мм, Волков, 6 дз, 1 задание
volkov-alexander-d/spbu_2020_c_homeworks pull request #17
Opened 2020-11-08 00:07 UTC by Alexander-Volkov-144

2020-11-08 00:21 UTC, Alexander-Volkov-144 commented
[input.txt](https://github.com/Alexander-Volkov-144/spbu_2020_c_homeworks/files/5505682/input.txt)

2020-11-11 14:58 UTC, nbirillo requested changes

2020-11-11 14:58 UTC, nbirillo commented on library/hashTable/hashTable.c
> +            if (table->hashTable[i]->numberOfProbes == numberOfProbes) {
Тоже лучше объединить условия

2020-11-11 14:58 UTC, nbirillo commented on library/hashTable/hashTable.c
> +bool notInArray(const int* array, int size, int value)
Может сделать `inArray` и при вызове проверять `!inArray` ? не инвертированные штуки лучше воспринимаются

2020-11-11 14:58 UTC, nbirillo commented on homework_6/task_6.1.c
> +int main()
Давай посомтрим на результат с тсвоим файлом
```
load factor: 0.359375
average number of probes: 1.478261
maximum number of probes: 7
elements with maximum number of probes: mastery 
number of words added: 46
number of empty buckets: 82
elements with biggest values:
i 5
a 3
like 3
and 3
of 3
am 2
painter 2
is 2
that 2
complete 1
```

Теперь посмотрим на твой текст, в частности на слово `a`
![image](https://user-images.githubusercontent.com/8993915/98824013-d337f280-2443-11eb-9125-9fdad429123d.png)

как видно, оно встречается 4 раза, у тебя 3

2020-11-11 14:58 UTC, nbirillo commented on homework_6/task_6.1.c
> +int main()
На пустом файле будет average number of probes: nan

2020-11-11 14:58 UTC, nbirillo commented on library/hashTable/hashTable.c
> +                    if (table->hashTable[j]->value > maximumValue || notFound) {
Может как-то можно вынести часть в функции или типа того, чтобы записать условие в одну строчку?

2020-11-11 14:58 UTC, nbirillo commented on homework_6/task_6.1.c
> +const int MAX_WORD_LENGTH = 20;
А что будет, если я введу слово с большей длиной? Можно выделять память динамически по длине слова

2020-11-11 14:58 UTC, nbirillo commented on library/hashTable/hashTable.c
> +bool addElement(HashTable* table, char* key, int value)
А как удалить элемент?

2020-11-11 17:03 UTC, Alexander-Volkov-144 commented on LICENSE
> +      You may addElementWithProbes Your own copyright statement to Your modifications and
Я видимо случайно переименовал когда менял название функции

2020-11-13 08:02 UTC, nbirillo requested changes

2020-11-15 07:16 UTC, nbirillo requested changes

2020-11-15 07:16 UTC, nbirillo commented on homework_6/task_6.1.c
>  int main()
У тебя по0прежнему не обрабатывается случай с пробелом
Если сделать файл:
```
i i i i i.
a
```
где после a нет пробела, то будет так:

```
load factor: 0.500000
average number of probes: 1.000000
maximum number of probes: 1
elements with maximum number of probes: i 
number of different added words: 1
number of empty buckets: 1
elements with biggest values:
i 5
```

при этом, если поставить пробел, то все будет ок

2020-11-15 07:16 UTC, nbirillo commented on library/fileProcessing/fileProcessing.c
> +}
Эти две функции не относятся в общем случае в обработке файлов. Это просто работа со строками - поэтому в этом модуле им не место)

2020-11-15 09:24 UTC, nbirillo commented
На всякий случай уточню, что сейчас реализация не покрывает дополнительное задание с независимой реализацией от hash-функции и пробирования

2020-11-15 18:58 UTC, volkov-alexander-d commented
@nbirillo

2020-11-15 19:02 UTC, nbirillo approved these changes
Отлично!

2020-11-15 19:02 UTC, merged