20.Б10-мм, Волков, 8 дз, 1 задание
volkov-alexander-d/spbu_2020_c_homeworks pull request #25
Opened 2020-11-25 14:12 UTC by volkov-alexander-d

2020-11-29 11:34 UTC, nbirillo requested changes
В целом все ок, небольшие комменты совсем

2020-11-29 11:34 UTC, nbirillo commented on homework_8/task_8.1.c
> +    removeDFA(dfa);
Давай вынесем в функцию, в которую будет передаваться список DFAState и которая удаляет каждый элемент из списка

2020-11-29 11:34 UTC, nbirillo commented on homework_8/task_8.1.c
> +bool checkString(char* string)
Я бы в принципе поделила бы на какие-то небольшие логические функции эту функцию, потому что сейчас не очень красиво выглядит. Но в целом если не придумаешь варианта лучше, можешь оставить так

2020-11-29 19:45 UTC, volkov-alexander-d commented on homework_8/task_8.1.c
> +bool checkString(char* string)
Я вынес часть в другую функцию, но мне кажется тут больше и не сделать. Если разделить создание состояний и переходов, то читаемость кода сильно упадет, так как вместо конкретных названий будут видны только индексы.

2020-12-01 08:53 UTC, nbirillo approved these changes
Ага, все хорошо, зачтено

2020-12-01 08:53 UTC, merged